#----------------------------------------------------------------------
# This file was generated by /Users/humberto.a.sanchez.ii/PycharmProjects/visual-dependencies/pyenv-3.11.7/bin/img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

embeddedImage = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAACXBIWXMAAAsTAAALEwEAmpwY'
    b'AAAELklEQVR4nO2bPWgUQRTH1zRJDrUQNdFYCYqFRBLtjKlEz0bmvWVMTJNWUWKiRmwsFPwk'
    b'reZDA2ksLoL4VSnC2eghBgTBSggkRNCrRIOZNTDyzju928+5zSYTd2/g3xwhN//fzXs7O/Oe'
    b'YSgOmU6vF6Z53EK8KxDfCoCvAsCyEKVO0RwKc0F8ayGOCYBuefToOiOqscDYTgtgXCDO6zar'
    b'DIXmCnBvAXFHaOOS80YBMCQQf+k2tMTVcUv29jZU96sj7rAQP+g2EOGKeCMBtiiZF6bZRjFV'
    b'/g86L92VxkTOVy3DL+STk+e1m/XRrDDN1sBfXriZvzIZCIC0bfi5bpOBECTnze4x39vbYCG+'
    b'dzWvCIC0CkwG6R3lN+fSBxjyNB8vAJQcL1cufcZ2lmd7h/mrD+MG4HtFKFgA477mR7KxAlCE'
    b'cOffDq9sk6NqNAYAfhR2jMXtrUwagAIExC6D9vZKAG48qgwN0s3Hzr9r75EpdjFQm9kFyeG0'
    b'/Ahd+iAAjBrFl4hgAGQ2QgAlbWWDchq7tO0QDYGYjzIEqgVA6mGndAH4Qs9/oRtAExvUBWDB'
    b'sH+oFPs+IaD65XYIOgBY5DcQgFvsJwrAxPI8BhML4DD0eeaCNOuLP4ADrN8TQCf0xx/AZ+Ry'
    b'HxtwmN/DzspZ5PoBtAy/CG1e9UDEDkGXecsNAB1rhYFA5p+eOKf8xXPI5X4YKGhOk3nLDcBK'
    b'KNvUIXMp5qupDUzmO2MIINvUISeMXYEAShBiBSBbNK8KgBQbANky84kDkLWZv79md3IAZF3M'
    b'v6w/mBwAOUWjNQCphK2ATF1bRWiQMnXtSQLQ7gAwWdeWHAC5Wg5gyUyCGZfYT1QOyLjEfi0H'
    b'pBIUArlaEmSRPwXyQxul9czwV6ZRWmf2x28F5Ic2yk93AsyXQ1hpAFMbwpsPOhApmVcGQFpp'
    b'APnOcBCCjsTKza9qAJaH6BK1XFVBtZmfHv0PAaRCXo25mf/2IEEALFWjNQCG2goQtgKJ1bQC'
    b'jkCf7GD9lRcnHsZmx/+FRUn0mR8AQQUS9hKZ1QSg/OpsBo8tB4AvjiKplRJViVVTRrOXFa/Q'
    b'IswBgoqkqM1EBwAqkau2lojuESMGMEI5oFsHAKoPpBK5pQJwW/rKIQDAqTVmLZWN6oBA9YFU'
    b'IkdVYmFDICyAQqks52tLxdL3dAAIkmv9QHQhMGbvFNHeAmfXITjjrB+IAAA9+n8ibrc3TNzS'
    b'bVhJ0QC47toyIxDfxB2AQHwt0+l6974hzpstxBntJv1EhxphAUw2LM5z3uLbOSZMs5W6q7Qb'
    b'9RIda4WAICYbFhdvN5/wNV8akvNNAuCVdrMRqbDsvdrlvAbFCXVX6dojRGIcQAiAa54xrzKI'
    b'HDUY/U8gCnMFGHU86pYyJO0YEbto/ywAcvQmpetV2vEr/5kLzWlYmOaxvzs8hfEbndt3Xb5o'
    b'UDIAAAAASUVORK5CYII=')

